### ISSUE TITLE
error when training with long audios.

### ISSUE THREAD

**Issue by loboere** [serp-ai/bark-with-voice-clone#4]
error when training with long audios.

when training with audio 5s-7s it works but at
training with an audio of 15s-20s gives me the following error
100%|██████████| 100/100 [00:03<00:00, 27.04it/s]
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
[<ipython-input-95-0063dbcae42b>](https://localhost:8080/#) in <cell line: 7>()
      5 """
      6 voice_name = "/content/bark-with-voice-clone/bark/assets/prompts/output5.npz" # use your custom voice name here if you have one
----> 7 audio_array = generate_audio(text_prompt, history_prompt=voice_name)

2 frames
[/usr/local/lib/python3.9/dist-packages/bark/generation.py](https://localhost:8080/#) in generate_coarse(x_semantic, history_prompt, temp, top_k, top_p, use_gpu, silent, max_coarse_history, sliding_window_len, model)
    522         else:
    523 
--> 524             x_history = np.load(
    525                 os.path.join(CUR_PATH, "assets", "prompts", f"{history_prompt}.npz")
    526             )

AssertionError:

**Comment by sould3mon** [comment]
tried it to with longer but indeed the same error.

i do wonder how much training there actualy is  i think there are allot of randomized settings inside the generate_audio since even running it twice one same text  with "cloned" voice produces very diffrent results.
so far none of ai voice generators i have tried actualy came close to resembling the input.
and even switching voice from female to male mid sentence.

not sure if there is a method to  train 1 voice on multiple short pieces of audio.

**Comment by francislabountyjr** [comment]
Use samples less than 7 seconds. The shorter the sample, the better the results in my limited testing so far

**Comment by devinschumacher** [comment]
@loboere 

We just launched our follow up to BARK -- an AI Voice Cloner Desktop App (runs locally, offline, super realistic voice cloning, data privacy, no coding needed)

👉 Check it out: https://github.com/serpapps/ai-voice-cloner
